config/routes.rb
Anpi1::Application.routes.draw do
  get "mobile/login"
  post "mobile/login" => "mobile_sessions#create", :as => "mobile_login"
  get "mobile/anpi" => "mobile#edit", :as => "mobile_edit"
  post "mobile/anpi" => "mobile#create", :as => "mobile_post"
  put "mobile/anpi" => "mobile#update", :as => "mobile_put"
  get "mobile/thanks" => "mobile#thanks", :as => "mobile_thanks"

	resources :mail_sends

  resources :member_infos

	get  "anpi_infos/:member_id/new" => "anpi_infos#new", :as => "new_anpi"
	get  "anpi_infos/:anpi_id/edit" => "anpi_infos#edit", :as => "edit_anpi"
	post "anpi_infos/:member_id" => "anpi_infos#create", :as => "save_anpi"
	put  "anpi_infos/:anpi_id" => "anpi_infos#update", :as => "update_anpi"

	resources :roles

	resources :teams

	resources :projects

	resources :mail_templates

	get "admins/new" => 'admins#new'
	post "admins/new" => 'admins#create'
	put "admins/update" => 'admins#update', :as => "change_password"
	get "admins" => 'admins#list', :as => "admins_list"
	get "admin" => 'admins#view', :as => "admin"
	delete "admins/:id" => "admins#destroy", :as => "delete_admin"
	get "sessions/delete" => 'sessions#delete', :as => "logout"
	post "sessions/new" => "sessions#create", :as => "login"

  get "status/" => "status#index", :as =>"status"
  get "status/delete_anpi" => "status#delete_anpi", :as =>"delete_anpi"

  post "/" => 'home#search', :as => "search_button"
	root :to => 'home#index'

end

app/models/mail_template.rb
class MailTemplate < ActiveRecord::Base
  attr_accessible :body, :mailName, :title
end

app/controllers/mail_templates_controller.rb
class MailTemplatesController < ApplicationController
  # GET /mail_templates
  # GET /mail_templates.json
  def index
    @mail_templates = MailTemplate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mail_templates }
    end
  end

  # GET /mail_templates/1
  # GET /mail_templates/1.json
  def show
    @mail_template = MailTemplate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mail_template }
    end
  end

  # GET /mail_templates/new
  # GET /mail_templates/new.json
  def new
    @mail_template = MailTemplate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mail_template }
    end
  end

  # GET /mail_templates/1/edit
  def edit
    @mail_template = MailTemplate.find(params[:id])
  end

  # POST /mail_templates
  # POST /mail_templates.json
  def create
    @mail_template = MailTemplate.new(params[:mail_template])

    respond_to do |format|
      if @mail_template.save
        format.html { redirect_to @mail_template, notice: 'Mail template was successfully created.' }
        format.json { render json: @mail_template, status: :created, location: @mail_template }
      else
        format.html { render action: "new" }
        format.json { render json: @mail_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mail_templates/1
  # PUT /mail_templates/1.json
  def update
    @mail_template = MailTemplate.find(params[:id])

    respond_to do |format|
      if @mail_template.update_attributes(params[:mail_template])
        format.html { redirect_to @mail_template, notice: 'Mail template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mail_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mail_templates/1
  # DELETE /mail_templates/1.json
  def destroy
    @mail_template = MailTemplate.find(params[:id])
    @mail_template.destroy

    respond_to do |format|
      format.html { redirect_to mail_templates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mail_templates_helper.rb
module MailTemplatesHelper
end

app/views/mail_templates/_form.html.erb
<%= form_for(@mail_template) do |f| %>
  <% if @mail_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mail_template.errors.count, "error") %> prohibited this mail_template from being saved:</h2>

      <ul>
      <% @mail_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    メールタイトル<br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    メール本文<br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    管理名<br />
    <%= f.text_field :mailName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mail_templates/edit.html.erb
<h1>メールテンプレート編集画面</h1>

<%= render 'form' %>

<%= link_to 'Show', @mail_template %> |
<%= link_to 'Back', mail_templates_path %>

app/views/mail_templates/index.html.erb
<h1>メールテンプレート管理画面</h1>

<table class="table table-striped table-hover table-condensed">
  <thead>
  <tr>
    <th></th><th></th><th></th>
    <th>
       <!-- <td><input type="button" value="決定"></td> -->
       <!--<input type="button" value="追加">-->
       <td>追加</td>
       <td><%= link_to add_icon, new_mail_template_path, :class=>"btn btn-primary" %></td>
    </th>
  </tr>


  <tr>
    <td>select</td>
    <td>メールタイトル(Title)</td>
    <td>メール本文(Body)</td>
    <td>管理名(Mailname)</td>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @mail_templates.each do |mail_template| %>
  <tr>
    <td><input type="radio" name="defult" ></td>
    <td><%= mail_template.title %></td>
    <td><%= mail_template.body %></td>
    <td><%= mail_template.mailName %></td>
    <!--<td><%= link_to 'Show', mail_template %></td>-->
    <td><%= link_to edit_icon, edit_mail_template_path(mail_template), :class=>"btn btn-info btn-mini" %></td>
    <td><%= link_to delete_icon, mail_template, :method=>"delete" ,:class=>"btn btn-danger btn-mini", data: { confirm:'Are you sure?'} %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

app/views/mail_templates/new.html.erb
<h1>New mail_template</h1>

<%= render 'form' %>

<%= link_to 'Back', mail_templates_path %>

app/views/mail_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @mail_template.title %>
</p>

<p>
  <b>Body:</b>
  <%= @mail_template.body %>
</p>

<p>
  <b>Mailname:</b>
  <%= @mail_template.mailName %>
</p>


<%= link_to 'Edit', edit_mail_template_path(@mail_template) %> |
<%= link_to 'Back', mail_templates_path %>