config/routes.rb
Anpi1::Application.routes.draw do
  get "mobile/login"
  post "mobile/login" => "mobile_sessions#create", :as => "mobile_login"
  get "mobile/anpi" => "mobile#edit", :as => "mobile_edit"
  post "mobile/anpi" => "mobile#create", :as => "mobile_post"
  put "mobile/anpi" => "mobile#update", :as => "mobile_put"
  get "mobile/thanks" => "mobile#thanks", :as => "mobile_thanks"

	resources :mail_sends

  resources :member_infos

	get  "anpi_infos/:member_id/new" => "anpi_infos#new", :as => "new_anpi"
	get  "anpi_infos/:anpi_id/edit" => "anpi_infos#edit", :as => "edit_anpi"
	post "anpi_infos/:member_id" => "anpi_infos#create", :as => "save_anpi"
	put  "anpi_infos/:anpi_id" => "anpi_infos#update", :as => "update_anpi"

	resources :roles

	resources :teams

	resources :projects

	resources :mail_templates

	get "admins/new" => 'admins#new'
	post "admins/new" => 'admins#create'
	put "admins/update" => 'admins#update', :as => "change_password"
	get "admins" => 'admins#list', :as => "admins_list"
	get "admin" => 'admins#view', :as => "admin"
	delete "admins/:id" => "admins#destroy", :as => "delete_admin"
	get "sessions/delete" => 'sessions#delete', :as => "logout"
	post "sessions/new" => "sessions#create", :as => "login"

  get "status/" => "status#index", :as =>"status"
  get "status/delete_anpi" => "status#delete_anpi", :as =>"delete_anpi"

  post "/" => 'home#search', :as => "search_button"
	root :to => 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
  attr_accessible :name, :password, :password_digest, :password_confirmation
end

app/models/anpi_info.rb
# -*- coding: utf-8 -*-
class AnpiInfo < ActiveRecord::Base
  attr_accessible :contact, :hurt_info, :location_info, :syachiku, :syachiku_reason, :family_info, :member_info_id
  belongs_to :member_info
  def self.find_or_new_for_user(id)
    begin
      result = find.by_member_info_id(id)
    rescue => e
      result = new
      result.member_info_id = id
    end
    result
  end
  def syachiku_unknown?
    syachiku == 0
  end
  def syachiku_ready?
    syachiku == 1
  end
  def syachiku_damepo?
    syachiku == 2
  end
  def syachiku_to_s
    if syachiku.nil? || syachiku == 0
      "不明"
    elsif syachiku == 1
      "出社可"
    elsif syachiku == 2
      "出社不可"
    end
  end

  def family_info_to_s
    if family_info.nil? || family_info == 0
      "未登録"
    elsif syachiku == 1
      "確認済み"
    elsif syachiku == 2
      "未確認"
    end
  end
end

app/models/mail_send.rb
class MailSend < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/mail_template.rb
class MailTemplate < ActiveRecord::Base
  attr_accessible :body, :mailName, :title
end

app/models/member_info.rb
class MemberInfo < ActiveRecord::Base
  attr_accessible :birthday, :full_name, :gender, :email,:project_id, :role_id, :team_id, :anpi_info_id
  has_one :anpi_info ,:dependent => :destroy
  belongs_to :project
  belongs_to :role
  belongs_to :team
  paginates_per 30
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :p_name
  paginates_per 30
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :role_name, :power
  paginates_per 30
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :last_send, :selected_mail_id
  belongs_to :selected_mail
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :team_name
  paginates_per 30
end

app/controllers/home_controller.rb
# -*- coding: utf-8 -*-
class HomeController < ApplicationController
  def index
    begin
      if Admin.find(current_admin.id).nil?
      end
    rescue => e
      session.delete :admin_id
    end
    if admin_signed_in?
      @member_infos = MemberInfo.find(:all).sort{|a,b| b.role.power <=> a.role.power}
    end
    @searched = {}
  end
  def search
    if params[:name] != ""
      @member_infos = MemberInfo.where :full_name => params[:name]
      if @member_infos == nil
        @member_infos = []
        flash[:alert] = "社員 #{params[:name]} は見つかりませんでした"
      end
      @searched = {}
      @searched["name"] = params[:name]
      render "index"
      return
    end
    if params[:project] != ""
      @member_infos = MemberInfo.where :project_id => params[:project]
      @searched = {}
      @searched["project"] = Project.find(params[:project]).p_name
      flash[:notice] = "#{@searched["project"]} 部を検索しました"
      render "index"
      return
    end
    if params[:team] != ""
      @member_infos = MemberInfo.where :team_id => params[:team]
      @searched = {}
      @searched["team"] = Team.find(params[:team]).team_name
      flash[:notice] = "#{@searched["team"]} 課を検索しました"
      render "index"
      return
    end
    flash[:alert] = "検索条件を入力してください"
    redirect_to root_path
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/anpi_infos_helper.rb
module AnpiInfosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_format(time)
    time.strftime("%Y-%m-%d %H:%M:%S")
  end

  # icons
  def edit_icon
    "<i class='icon-edit'></i>".html_safe
  end
  def delete_icon
    "<i class='icon-trash'></i>".html_safe
  end
  def add_icon
    "<i class='icon-plus'></i>".html_safe
  end
  def right_arrow
    "<i class='icon-chevron-right'></i>".html_safe
  end
  def search_icon
    "<i class='icon-search'></i>".html_safe
  end

  def unknown_members_list
    []
  end
end

app/helpers/mail_sends_helper.rb
module MailSendsHelper
end

app/helpers/member_infos_helper.rb
module MemberInfosHelper
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password_hash %><br />
    <%= f.text_field :password_hash %>
  </div>
  <div class="field">
    <%= f.label :password_salt %><br />
    <%= f.text_field :password_salt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/list.html.erb
<h1>管理者一覧</h1>
<table class="table table-striped table-hover table-condensed">
  <thead>
  <th>ユーザ名</th>
  <th>登録日時</th>
  <th>操作</th>
  </thead>
  <tbody>
  <% @admins.each do |admin| %>
  <tr>
     <td>
      <% if admin == current_admin %>
        <%= link_to admin.name, admin_path %>
      <% else %>
        <%= admin.name %>
      <% end %>
      </td>
      <td> <%= time_format(admin.created_at) %> </td>
      <td>
        <% if admin == current_admin %>
          <%= link_to "編集", admin_path, :method=>"get", :class=>"btn btn-info btn-mini" %>
        <% else %>
          <%= link_to "削除", delete_admin_path(admin.id), :method=>"delete", :class=>"btn btn-danger btn-mini", :confirm=>"ユーザ #{admin.name} を削除してよろしいですか？"%>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= button_to "新規作成", admins_new_path, :class=>"btn btn-primary",:method=>:get %>

app/views/admins/login.html.erb
<h1>ログイン</h1>

<% if current_user == nil %>
  <%= link_to "ログイン", sessions_path %>
<% else %>
  <%= link_to 'ログアウト', session_path(current_user.id), :confirm => 'ログアウトしますか？', :method => :delete %>
<% end %>

<%= form_for @admin do |f| %>
  <% if @admin.errors.any?%>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @admin.errors.full_messages %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/admins/new.html.erb
<h1>管理者登録</h1>
<%= form_tag "/admins/new" do |f| %>
  <%= label_tag "ユーザ名" %>
  <%= text_field_tag :name %>
  <%= label_tag "パスワード" %>
  <%= password_field_tag :password %>
  <%= label_tag "パスワード（確認）" %>
  <%= password_field_tag :password_confirmation %>
  <br>
  <%= submit_tag "登録",:class=>"btn btn-primary", :target=>admins_new_path %>
<% end %>

app/views/admins/show.html.erb
<p>
ユーザ名:
<%= current_admin.name %>
</p>

<p>
登録日時:
<%= current_admin.created_at %>
</p>

<p>
パスワード変更:
<%= form_tag change_password_path, :method=>:put do |f| %>
  <%= label_tag "新しいパスワード" %>
  <%= password_field_tag :password %>
  <%= label_tag "新しいパスワード（確認）" %>
  <%= password_field_tag :password_confirmation %>
  <%= label_tag "古いパスワード" %>
  <%= password_field_tag :old_password %>
  <br>
  <%= submit_tag "パスワード変更",:class=>"btn btn-primary", :target=>admins_new_path %>
<% end %>
</p>
<%= link_to "管理者一覧", admins_list_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>安否確認システム</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style>
    body {
      padding-top: 60px
    }
  </style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="/">安否情報確認</a>
      <div class="nav-collapse collapse">
        <ul class="nav-collapse collapse">
          <% if admin_signed_in? %>
          <li class="">
            管理者：<%= link_to current_admin.name, admin_path %>
            <%= link_to "<i class='icon-share-alt'></i>ログアウト".html_safe, logout_path %>
          </li>
          <% else %>
          <li class="">管理者：ログインしていません</li>
          <% end %>
          </ul>
      </div>
    </div>
  </div>
</div>
<% if admin_signed_in? %>
<table>
  <tr>
    <th>
　　　　前回の送信日時<br>
        <textarea>2011/03/11 13:30くらい</textarea><br>
        <input type="button" value="メール送信" onClick="location.href='mail_sends'"><br>
        <input type="button" value="メールテンプレート" onClick="location.href='mail_templates'"><br>
        <input type="button" value="管理者一覧" onClick="location.href='admin_tables'"><br>
        <input type="button" value="災害発生"><br>
        <!-- このボタンは安否をいっせいに否にするボタンである(ｷﾘｯ -->
        <input type="button" value="ログアウト" onClick="location.href='logins'"><br>
        <input type="button" value="ゆーざろぐいんぺーじへ" onClick="location.href='user_logins'"><br>
        ↑仮のボタンですよぉ<br>
    </th>
    <th><%= yield %></th>
  </tr>
</table>
<% elsif params[:controller] == "home" || params[:controller] == "admins" %>
  <%= yield %>
<% else %>
<%= params[:controller] %>
  ログインしてください。
  <% link_to "ログイン画面",root_path %>
<% end %>  
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>安否確認システム</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style>
    body {
      padding-top: 60px
    }
  </style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="/">安否情報確認</a>
      <div class="nav-collapse collapse">
        <ul class="nav-collapse collapse">
          <% if admin_signed_in? %>
          <li class="">
            管理者：<%= link_to current_admin.name, admin_path %>
            <%= link_to "<i class='icon-share-alt'></i>ログアウト".html_safe, logout_path %>
          </li>
          <% else %>
          <li class="">管理者：ログインしていません</li>
          <% end %>
          </ul>
      </div>
    </div>
  </div>
</div>
<% if admin_signed_in? %>

<% unless notice.nil?%>
<p class="alert-success"><i class="icon-ok-circle"></i> <%= notice %></p>
<% end %>

<% unless alert.nil?%>
<p class="alert-error"><i class="icon-remove-sign"></i> <%= alert %></p>
<% end %>


<div class="container">
  <div class="row">
    <div class="span3">
      <h4>前回の送信日時</h4>
      <ul class="nav nav-list">
        <li class="nav-header">メニュー</li>
	<li>
	  <%= link_to "<i class='icon-chevron-right'></i>トップ".html_safe, root_path -%>
	</li>
        <li class="divider"></li>
        <li>
          <%= link_to "<i class='icon-chevron-right'></i>管理者一覧".html_safe, admins_list_path -%>
        </li>
	<li>
	  <%= link_to "<i class='icon-chevron-right'></i>メールテンプレート".html_safe, mail_templates_path -%>
	</li>
	<li>
	  <!-- このボタンは安否をいっせいに否にするボタンである(ｷﾘｯ -->
	  <%= link_to "<i class='icon-certificate'></i>災害発生".html_safe, delete_anpi_path, :confirm=>"安否情報を削除して安否登録要請メールを一斉送信します、よろしいですか？" -%>
	</li>
	<li>
	  <%= link_to "<i class='icon-chevron-right'></i>ステータス".html_safe, status_path -%>
	</li>
	<li>
	  <%= link_to "<i class='icon-chevron-right'></i>部一覧".html_safe, projects_path -%>
	</li>
	<li>
	  <%= link_to "<i class='icon-chevron-right'></i>課一覧".html_safe, teams_path -%>
	</li>
	<li>
	  <%= link_to "<i class='icon-chevron-right'></i>役職一覧".html_safe, roles_path -%>
	</li>
      </ul>
      </div>
    <div class="span9">
      <%= yield %>
    </div>
  </div>
</div>

<% elsif params[:controller] == "home" || params[:controller] == "admins" %>
<%= yield %>
<% else %>
<%= params[:controller] %>
  ログインしてください。
  <% link_to "ログイン画面",root_path %>
<% end %>  
</body>
</html>

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>安否確認システム</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% unless notice.nil?%>
<p class="alert-success"><i class="icon-ok-circle"></i> <%= notice %></p>
<% end %>

<% unless alert.nil?%>
<p class="alert-error"><i class="icon-remove-sign"></i> <%= alert %></p>
<% end %>

<h3>安否確認システム</h3>
<%= yield %>

app/views/msend/send1.text.erb
Msend#send1

<%= @greeting %>, find me in app/views/app/views/msend/send1.text.erb