config/routes.rb
Anpi1::Application.routes.draw do
  get "mobile/login"
  post "mobile/login" => "mobile_sessions#create", :as => "mobile_login"
  get "mobile/anpi" => "mobile#edit", :as => "mobile_edit"
  post "mobile/anpi" => "mobile#create", :as => "mobile_post"
  put "mobile/anpi" => "mobile#update", :as => "mobile_put"
  get "mobile/thanks" => "mobile#thanks", :as => "mobile_thanks"

	resources :mail_sends

  resources :member_infos

	get  "anpi_infos/:member_id/new" => "anpi_infos#new", :as => "new_anpi"
	get  "anpi_infos/:anpi_id/edit" => "anpi_infos#edit", :as => "edit_anpi"
	post "anpi_infos/:member_id" => "anpi_infos#create", :as => "save_anpi"
	put  "anpi_infos/:anpi_id" => "anpi_infos#update", :as => "update_anpi"

	resources :roles

	resources :teams

	resources :projects

	resources :mail_templates

	get "admins/new" => 'admins#new'
	post "admins/new" => 'admins#create'
	put "admins/update" => 'admins#update', :as => "change_password"
	get "admins" => 'admins#list', :as => "admins_list"
	get "admin" => 'admins#view', :as => "admin"
	delete "admins/:id" => "admins#destroy", :as => "delete_admin"
	get "sessions/delete" => 'sessions#delete', :as => "logout"
	post "sessions/new" => "sessions#create", :as => "login"

  get "status/" => "status#index", :as =>"status"
  get "status/delete_anpi" => "status#delete_anpi", :as =>"delete_anpi"

  post "/" => 'home#search', :as => "search_button"
	root :to => 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
  attr_accessible :name, :password, :password_digest, :password_confirmation
end

app/models/anpi_info.rb
# -*- coding: utf-8 -*-
class AnpiInfo < ActiveRecord::Base
  attr_accessible :contact, :hurt_info, :location_info, :syachiku, :syachiku_reason, :family_info, :member_info_id
  belongs_to :member_info
  def self.find_or_new_for_user(id)
    begin
      result = find.by_member_info_id(id)
    rescue => e
      result = new
      result.member_info_id = id
    end
    result
  end
  def syachiku_unknown?
    syachiku == 0
  end
  def syachiku_ready?
    syachiku == 1
  end
  def syachiku_damepo?
    syachiku == 2
  end
  def syachiku_to_s
    if syachiku.nil? || syachiku == 0
      "不明"
    elsif syachiku == 1
      "出社可"
    elsif syachiku == 2
      "出社不可"
    end
  end

  def family_info_to_s
    if family_info.nil? || family_info == 0
      "未登録"
    elsif syachiku == 1
      "確認済み"
    elsif syachiku == 2
      "未確認"
    end
  end
end

app/models/mail_send.rb
class MailSend < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/mail_template.rb
class MailTemplate < ActiveRecord::Base
  attr_accessible :body, :mailName, :title
end

app/models/member_info.rb
class MemberInfo < ActiveRecord::Base
  attr_accessible :birthday, :full_name, :gender, :email,:project_id, :role_id, :team_id, :anpi_info_id
  has_one :anpi_info ,:dependent => :destroy
  belongs_to :project
  belongs_to :role
  belongs_to :team
  paginates_per 30
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :p_name
  paginates_per 30
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :role_name, :power
  paginates_per 30
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :last_send, :selected_mail_id
  belongs_to :selected_mail
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :team_name
  paginates_per 30
end

app/controllers/home_controller.rb
# -*- coding: utf-8 -*-
class HomeController < ApplicationController
  def index
    begin
      if Admin.find(current_admin.id).nil?
      end
    rescue => e
      session.delete :admin_id
    end
    if admin_signed_in?
      @member_infos = MemberInfo.find(:all).sort{|a,b| b.role.power <=> a.role.power}
    end
    @searched = {}
  end
  def search
    if params[:name] != ""
      @member_infos = MemberInfo.where :full_name => params[:name]
      if @member_infos == nil
        @member_infos = []
        flash[:alert] = "社員 #{params[:name]} は見つかりませんでした"
      end
      @searched = {}
      @searched["name"] = params[:name]
      render "index"
      return
    end
    if params[:project] != ""
      @member_infos = MemberInfo.where :project_id => params[:project]
      @searched = {}
      @searched["project"] = Project.find(params[:project]).p_name
      flash[:notice] = "#{@searched["project"]} 部を検索しました"
      render "index"
      return
    end
    if params[:team] != ""
      @member_infos = MemberInfo.where :team_id => params[:team]
      @searched = {}
      @searched["team"] = Team.find(params[:team]).team_name
      flash[:notice] = "#{@searched["team"]} 課を検索しました"
      render "index"
      return
    end
    flash[:alert] = "検索条件を入力してください"
    redirect_to root_path
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all.sort{|a,b| b.power <=> a.power}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    redirect_to roles_path
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/anpi_infos_helper.rb
module AnpiInfosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_format(time)
    time.strftime("%Y-%m-%d %H:%M:%S")
  end

  # icons
  def edit_icon
    "<i class='icon-edit'></i>".html_safe
  end
  def delete_icon
    "<i class='icon-trash'></i>".html_safe
  end
  def add_icon
    "<i class='icon-plus'></i>".html_safe
  end
  def right_arrow
    "<i class='icon-chevron-right'></i>".html_safe
  end
  def search_icon
    "<i class='icon-search'></i>".html_safe
  end

  def unknown_members_list
    []
  end
end

app/helpers/mail_sends_helper.rb
module MailSendsHelper
end

app/helpers/member_infos_helper.rb
module MemberInfosHelper
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/index.html.erb
<h1>安否確認システム</h1>
<br />

<%= form_tag root_path, :controller=>:home_controller, :method=>:post do %>
  部署名:<%= select_tag :project, options_for_select(Project.all.map{|p|[p.p_name, p.id]}), :include_blank =>true %>
  課名:<%= select_tag :team, options_for_select(Team.all.map{|p|[p.team_name, p.id]}), :include_blank =>true %>
  氏名:<%= text_field_tag :name, "" %>
  <%= submit_tag "検索", :class=>"btn btn-info" %>
<% end %>

<% if @searched != {} %>
<p>
  検索条件
  <% if @searched["name"] %>
    氏名: <%= @searched["name"] %>
  <% end %>
  <% if @searched["project"] %>
    部: <%= @searched["project"] %>
  <% end %>
  <% if @searched["team"] %>
    課: <%= @searched["team"] %>
  <% end %>
</p>
<% end %>

<% unless current_admin %>
  <%= form_tag login_path do %>
  <%= label_tag :name %>
  <%= text_field_tag :name, params[:name] %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <br>
  <%= submit_tag "ログイン", :class=>"btn btn-primary" %>
  <br>
  <% end %>
  <%= button_to "登録(このボタンはリリース時は消します)", admins_new_path, :class=>"btn", :method=>:get %>
<% else %>


<p>
  <span class="label">
  未登録:
  <%= @member_infos.count{|member| member.anpi_info.nil? || member.anpi_info.syachiku_unknown?} %>件
  </span>
  <span class="label label-success">
  出社可:
  <%= @member_infos.count{|member| member.anpi_info && member.anpi_info.syachiku == 1} %>件
  </span>
  <span class="label label-important">
  出社不可:
  <%= @member_infos.count{|member| member.anpi_info && member.anpi_info.syachiku == 2} %>件
  </span>
</p>

<p>社員一覧</p>
<table class="table table-condened table-hover">
  <thead>
  <th>氏名</th>
  <th>生年月日</th>
  <th>性別</th>
  <th>部</th>
  <th>課</th>
  <th>役職</th>
  <th>安否情報編集</th>
  <th>操作</th>
  </thead>
  <tbody>
    <% @member_infos.each do |member| %>
  <% if member.anpi_info.nil? || member.anpi_info.syachiku_unknown? %>
    <tr>
  <% elsif member.anpi_info.syachiku == 1 %>
    <tr class="info">
  <% elsif member.anpi_info.syachiku == 2 %>
    <tr class="error">
  <% else %>
    <tr class="warning">
  <% end %>

  <% if member.anpi_info.nil? || member.anpi_info.syachiku_unknown? %>
    <td> <%= link_to member.full_name, new_anpi_path(member) %> </td>
  <% else %>
    <td> <%= link_to member.full_name, edit_anpi_path(member.anpi_info, member.anpi_info) %> </td>
  <% end %>
    <td> <%= member.birthday %> </td>
    <td> <%= member.gender %> </td>
    <td> <%= member.project.p_name %> </td>
    <td> <%= member.team.team_name %> </td>
    <td> <%= member.role.role_name %> </td>
  <% if member.anpi_info.nil? || member.anpi_info.syachiku_unknown? %>
    <td> <%= link_to "安否情報", new_anpi_path(member),:class=>"btn btn-mini btn-info" %> </td>
<% else %>
    <td> <%= link_to "安否情報", edit_anpi_path(member.anpi_info),:class=>"btn btn-mini btn-success" %> </td>
  <% end %>
    <td>
      <%= link_to edit_icon, edit_member_info_path(member),:class=>"btn btn-mini btn-primary" %>
      <%= link_to delete_icon, member,:class=>"btn btn-mini btn-danger",:method=>:delete,:data=> { confirm: "社員 #{member.full_name} の情報を消去して宜しいですか？" } %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>
<%= link_to add_icon, new_member_info_path, :class=>"btn btn-primary",:method=>:get %>
<% end %>