config/routes.rb
Anpi1::Application.routes.draw do
  get "mobile/login"
  post "mobile/login" => "mobile_sessions#create", :as => "mobile_login"
  get "mobile/anpi" => "mobile#edit", :as => "mobile_edit"
  post "mobile/anpi" => "mobile#create", :as => "mobile_post"
  put "mobile/anpi" => "mobile#update", :as => "mobile_put"
  get "mobile/thanks" => "mobile#thanks", :as => "mobile_thanks"

	resources :mail_sends

  resources :member_infos

	get  "anpi_infos/:member_id/new" => "anpi_infos#new", :as => "new_anpi"
	get  "anpi_infos/:anpi_id/edit" => "anpi_infos#edit", :as => "edit_anpi"
	post "anpi_infos/:member_id" => "anpi_infos#create", :as => "save_anpi"
	put  "anpi_infos/:anpi_id" => "anpi_infos#update", :as => "update_anpi"

	resources :roles

	resources :teams

	resources :projects

	resources :mail_templates

	get "admins/new" => 'admins#new'
	post "admins/new" => 'admins#create'
	put "admins/update" => 'admins#update', :as => "change_password"
	get "admins" => 'admins#list', :as => "admins_list"
	get "admin" => 'admins#view', :as => "admin"
	delete "admins/:id" => "admins#destroy", :as => "delete_admin"
	get "sessions/delete" => 'sessions#delete', :as => "logout"
	post "sessions/new" => "sessions#create", :as => "login"

  get "status/" => "status#index", :as =>"status"
  get "status/delete_anpi" => "status#delete_anpi", :as =>"delete_anpi"

  post "/" => 'home#search', :as => "search_button"
	root :to => 'home#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :role_name, :power
  paginates_per 30
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all.sort{|a,b| b.power <=> a.power}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    redirect_to roles_path
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for @role, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :role_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :role_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :power, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :power, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                roles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/roles/index.html.erb
<h1>役職一覧</h1>

<table class="table table-striped table-hover table-condensed">
  <thead>
  <tr>
    <th>役職名</th>
    <th>偉さ</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @roles.each do |role| %>
  <tr>
    <td><%= role.role_name %></td>
    <td><%= role.power %></td>
    <td><%= link_to edit_icon, edit_role_path(role), :class => "btn btn-primary btn-mini" , :method=>:get %>
    <%= link_to delete_icon, role,:method=>:delete, :class => "btn btn-danger btn-mini",:data=> { confirm: "役職 #{role.role_name} を消去して宜しいですか？" } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to add_icon, new_role_path, :class =>"btn btn-primary", :method =>:get %>

app/views/roles/new.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/roles/show.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:role_name) %>:</strong></dt>
  <dd><%= @role.role_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:power) %>:</strong></dt>
  <dd><%= @role.power %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              roles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_role_path(@role), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              role_path(@role),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>